CREATE TABLE skill (
    id SERIAL PRIMARY KEY,
    index TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL UNIQUE,
    ability_score_id INTEGER NOT NULL REFERENCES ability_score(id) ON DELETE CASCADE ON UPDATE CASCADE
);