DROP TABLE IF EXISTS monsters;

CREATE TABLE monsters (
    id SERIAL PRIMARY KEY,
    index TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL UNIQUE,
    size TEXT NOT NULL,
    type TEXT NOT NULL,
    subtype TEXT,
    alignment TEXT NOT NULL,
    armor_class INTEGER NOT NULL,
    hit_points INTEGER NOT NULL,
    hit_dice TEXT NOT NULL,
    speed JSONB NOT NULL,
    xp INTEGER NOT NULL,
    strength INTEGER NOT NULL,
    dexterity INTEGER NOT NULL,
    constitution INTEGER NOT NULL,
    intelligence INTEGER NOT NULL,
    wisdom INTEGER NOT NULL,
    charisma INTEGER NOT NULL,
    proficiencies JSONB,
    damage_vulnerabilities TEXT[],
    damage_resistances TEXT[],
    damage_immunities TEXT[],
    condition_immunities TEXT[],
    senses JSONB,
    languages TEXT,
    challenge_rating NUMERIC (3,1) NOT NULL,
    special_abilities JSONB,
    actions JSONB NOT NULL,
    legendary_actions JSONB,
    description TEXT[] NOT NULL
);