DROP TABLE IF EXISTS race_traits;

CREATE TABLE race_traits (
    id SERIAL PRIMARY KEY,
    race_id INTEGER REFERENCES races(id) ON DELETE CASCADE ON UPDATE CASCADE,
    trait_id INTEGER REFERENCES traits(id) ON DELETE CASCADE ON UPDATE CASCADE
);