-- CREATE TABLE subspecies (
--   id SERIAL PRIMARY KEY,
--   slug TEXT UNIQUE NOT NULL,                            -- e.g., 'high-elf'
--   species_slug TEXT REFERENCES species(slug) ON DELETE CASCADE ON UPDATE CASCADE,
--   name TEXT NOT NULL,
--   description TEXT[] NOT NULL,
--   UNIQUE (species_slug, name)
-- );