// seedDeitiesBatch1.js
import db from '../client.js';

export async function seedDeitiesBatch1() {
  try {
    await db.query('TRUNCATE deities RESTART IDENTITY CASCADE');
    await db.query(`
      INSERT INTO deities (index, name, alignment, domain, description) VALUES
      ('bahamut','Bahamut','Lawful Good',
         ARRAY['Protection','Justice','Dragon','Life'],
         ARRAY['Platinum Dragon, god of justice and good dragons']),
      ('tiamat','Tiamat','Lawful Evil',
         ARRAY['Greed','Trickery','Dragon'],
         ARRAY['Five‑headed queen of evil dragons']),
      ('io','Io','Neutral',
         ARRAY['Balance','Creation','Dragon'],
         ARRAY['Also called Asgorath, creator of dragonkind']),
      ('astilabor','Astilabor','Neutral',
         ARRAY['Wealth','Acquisitiveness','Dragon'],
         ARRAY['Goddess of greed and dragon wealth']),
      ('hlal','Hlal','Neutral Good',
         ARRAY['Joy','Inspiration','Dragon'],
         ARRAY['Goddess of humor and storytelling']),
      ('lendys','Lendys','Lawful',
         ARRAY['Justice','Balance','Dragon'],
         ARRAY['Goddess of justice among dragons']),
      ('tamara','Tamara','Neutral Good',
         ARRAY['Mercy','Life','Dragon'],
         ARRAY['Goddess of forgiveness and healing']),
      ('corellon-larethian','Corellon Larethian','Chaotic Good',
         ARRAY['Magic','Art','Elven','Arcana'],
         ARRAY['Elven creator deity of magic and arts']),
      ('moradin','Moradin','Lawful Good',
         ARRAY['Forge','Creation','Dwarven'],
         ARRAY['Dwarven god of smithing and creation']),
      ('gruumsh','Gruumsh','Chaotic Evil',
         ARRAY['War','Conquest','Orc'],
         ARRAY['One‑eyed chief deity of the orcs']),
      ('lolth','Lolth','Chaotic Evil',
         ARRAY['Trickery','Deception','Spider','Drow'],
         ARRAY['Drow spider queen and goddess of chaos']),
      ('eilistraee','Eilistraee','Chaotic Good',
         ARRAY['Beauty','Freedom','Moon','Drow'],
         ARRAY['Goddess of song, dance, and moonlit freedom']),
      ('ioun','Ioun','Neutral',
         ARRAY['Knowledge','Skill','Magic'],
         ARRAY['Goddess of knowledge, skill, and prophecy']),
      ('boccob','Boccob','Neutral',
         ARRAY['Arcana','Knowledge','Balance'],
         ARRAY['God of magic, foresight, and balance']),
      ('nerull','Nerull','Neutral Evil',
         ARRAY['Death','Decay'],
         ARRAY['God of death and the undead']),
      ('heironeous','Heironeous','Lawful Good',
         ARRAY['Valor','Justice','War'],
         ARRAY['God of chivalry, justice, and valor']),
      ('pholtus','Pholtus','Lawful Good',
         ARRAY['Light','Law','Sun'],
         ARRAY['God of light, law, and order']),
      ('rao','Rao','Neutral Good',
         ARRAY['Peace','Protection','Restoration'],
         ARRAY['God of serenity, peace, and reason']),
      ('celestian','Celestian','Neutral',
         ARRAY['Stars','Magic','Oath'],
         ARRAY['God of stars, navigation, and oaths']),
      ('elonna','Ehlonna','Neutral Good',
         ARRAY['Nature','Fertility','Forests'],
         ARRAY['Goddess of forests, flora, and fertility']),
      ('pelor','Pelor','Neutral Good',
         ARRAY['Sun','Healing','Justice'],
         ARRAY['God of the sun, healing, and agriculture']),
      ('st-cuthbert','Saint Cuthbert','Lawful Neutral',
         ARRAY['Zeal','Wisdom','Justice'],
         ARRAY['God of common sense, zeal, and retribution']),
      ('olidammara','Olidammara','Chaotic Neutral',
         ARRAY['Luck','Music','Roguery'],
         ARRAY['Trickster god of revelry and rogues']),
      ('erythnul','Erythnul','Chaotic Evil',
         ARRAY['Slaughter','Envy','Chaos'],
         ARRAY['God of slaughter, envy, and chaos']),
      ('fharlanghn','Fharlanghn','Neutral',
         ARRAY['Travel','Luck','Distance'],
         ARRAY['God of travel, horizons, and luck']),
      ('hextor','Hextor','Lawful Evil',
         ARRAY['War','Discord','Oppression'],
         ARRAY['God of war, discord, mass slaughter']),
      ('kord','Kord','Chaotic Good',
         ARRAY['Athletics','Strength','Storm'],
         ARRAY['God of strength, athletics, storms, and competition']),
      ('stataurus','St. Cuthbert','Lawful Neutral',
         ARRAY['Zeal','Judgment'],
         ARRAY['God of retribution and common sense']),  -- duplicate? remove accordingly
      ('vecna','Vecna','Neutral Evil',
         ARRAY['Knowledge','Secrets','Undeath'],
         ARRAY['Lich‑god of secrets, necromancy, and undeath']),
      ('wee-jas','Wee Jas','Lawful Neutral',
         ARRAY['Magic','Death','Protection'],
         ARRAY['Goddess of magic, death, vanity, and law']),
      ('bane','Bane','Lawful Evil',
         ARRAY['War','Tyranny','Fear'],
         ARRAY['God of tyranny, fear, and conquest']),
      ('lathander','Lathander','Neutral Good',
         ARRAY['Life','Light','Renewal'],
         ARRAY['God of dawn, birth, and renewal']),
      ('torm','Torm','Lawful Good',
         ARRAY['Duty','Law','War'],
         ARRAY['God of duty, loyalty, and righteousness']),
      ('tyr','Tyr','Lawful Good',
         ARRAY['Justice','War','Law'],
         ARRAY['God of justice and lawful valor']),
      ('mystra','Mystra','Neutral Good',
         ARRAY['Magic','Knowledge','Weave'],
         ARRAY['Goddess of magic, the Weave, and arcane knowledge']),
      ('selune','Selûne','Chaotic Good',
         ARRAY['Moon','Light','Navigation'],
         ARRAY['Goddess of the moon, stars, and guidance']),
      ('shar','Shar','Neutral Evil',
         ARRAY['Darkness','Loss','Secrets'],
         ARRAY['Goddess of darkness, loss, and secrets']),
      ('tempus','Tempus','Neutral',
         ARRAY['War','Honor','Battle'],
         ARRAY['God of war, valor, and honor']),
      ('tymora','Tymora','Chaotic Good',
         ARRAY['Luck','Good Fortune','Adventure'],
         ARRAY['Goddess of luck, good fortune, and bold action'])
      ;
    `);
    console.log('✅ Deities Batch1 seeded');
  } catch (err) {
    console.error('❌ seedDeitiesBatch1 error', err);
  }
}